version: '1.2.{build}'

install:
  - ps: |
  Install-PackageProvider Nuget –force –verbose
  Set-PSRepository -Name PSGallery -InstallationPolicy Trusted 
  Install-Module -Name PSScriptAnalyzer

build: false

test_script:
  - ps: |
  $res = Invoke-ScriptAnalyzer .\RedSeal.ps*
  if ($res.Count -gt 0) { throw "$($res.Count) tests failed."}

after_build:
  - ps: Get-ChildItem .\*.nupkg | % {Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - path: build
    name: Redseal
    type: NuGetPackage

deploy:
  - provider: NuGet
    name: production
    on:
      appveyor_repo_tag: true
    artifact: /*\.nupkg/
    
  - provider: GitHub
    on:
      appveyor_repo_tag: true
    artifact: /*\.nupkg/
    description: 'Release description'
    
environment:
  NuGetApiKey:
    secure: 4HmcYasXmCps4URyA53dat5hyqyvIQzTE3IS7GcVFuJgad2Bn1hkKoE8qUH9fpso
