version: '1.2.{build}'

install:
  - ps: Install-PackageProvider Nuget –Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted 
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
  - ps: |
      $res = Invoke-ScriptAnalyzer -Path  -Settings .\PSRedSeal\PSScriptAnalyzerSettings.psd1
      # Format the results
      $header = “<testsuite tests=`”$($results.Count)`”>”
      $body = $results | ForEach-Object {“<testcase classname=`”analyzer`” name=`”$($_.RuleName)`”><failure type=`”$($_.ScriptName)`”>$($_.Message)</failure></testcase>”}
      $footer = “</testsuite>”
      $header + $body + $footer | out-file .\TestsResults.xml
      # Upload results
      $wc = New-Object ‘System.Net.WebClient’
      $wc.UploadFile(“https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)“, (Resolve-Path .\TestsResults.xml))
      # Fail if there are issues
      if ($res.Count -gt 0) { throw "$($res.Count) tests failed."}

environment:
    nuget_api_key:
      secure: 4HmcYasXmCps4URyA53dat5hyqyvIQzTE3IS7GcVFuJgad2Bn1hkKoE8qUH9fpso

after_build:
  - 7z a redseal.zip %APPVEYOR_BUILD_FOLDER%\PSRedSeal\*
  - ps: Get-ChildItem .\*.zip | % {Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - path: build
    name: PSRedSeal
    type: NuGetPackage
    api_key:
      secure: 4HmcYasXmCps4URyA53dat5hyqyvIQzTE3IS7GcVFuJgad2Bn1hkKoE8qUH9fpso

deploy:
  - provider: Script
    name: production
    on:
      appveyor_repo_tag: true
    ps: Publish-Module $ENV:APPVEYOR_BUILD_FOLDER\PSRedSeal -NuGetApiKey $Env:NUGET_API_KEY
    
  - provider: GitHub
    on:
      appveyor_repo_tag: true
    description: 'Release description'
    auth_token:
      secure: ANstD90CPeaEG/JTUq4pw8/s0UaGDmIomjvVt3f2tPqnFdD2VhPF8DOlP5AAP2lX
