install:
  - ps: Install-PackageProvider Nuget –force –verbose
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted 
  - ps: Install-Module -Name PSScriptAnalyzer

build: false

test_script:
  - ps: $res = Invoke-ScriptAnalyzer .\RedSeal.ps*
  - ps: if ($res.Count -gt 0) { throw "$($res.Count) tests failed."}