version: '1.2.{build}'

install:
  - ps: nstall-PackageProvider Nuget –Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted 
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
  - ps: >-
      $res = Invoke-ScriptAnalyzer .\RedSeal.ps*
      # Format the results
      $header = “<testsuite tests=`”$($results.Count)`”>”
      $body = $results | ForEach-Object {“<testcase classname=`”analyzer`” name=`”$($_.RuleName)`”><failure type=`”$($_.ScriptName)`”>$($_.Message)</failure></testcase>”}
      $footer = “</testsuite>”
      $header + $body + $footer | out-file .\TestsResults.xml
      # Upload results
      $wc = New-Object ‘System.Net.WebClient’
      $wc.UploadFile(“https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)“, (Resolve-Path .\TestsResults.xml))
      # Fail if there are issues
      if ($res.Count -gt 0) { throw "$($res.Count) tests failed."}

after_test:
  on:
    appveyor_repo_tag: true
  ps: Publish-Module -Name "RedSeal" -NuGetApiKey $Env:nuget_api_key

environment:
    nuget_api_key:
      secure: 4HmcYasXmCps4URyA53dat5hyqyvIQzTE3IS7GcVFuJgad2Bn1hkKoE8qUH9fpso

after_build:
  - ps: Get-ChildItem .\*.nupkg | % {Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - path: build
    name: RedSeal
    type: NuGetPackage
    api_key:
      secure: 4HmcYasXmCps4URyA53dat5hyqyvIQzTE3IS7GcVFuJgad2Bn1hkKoE8qUH9fpso


deploy:
  - provider: NuGet
    name: production
    on:
      appveyor_repo_tag: true
    
  - provider: GitHub
    on:
      appveyor_repo_tag: true
    description: 'Release description'
    auth_token:
      secure: ANstD90CPeaEG/JTUq4pw8/s0UaGDmIomjvVt3f2tPqnFdD2VhPF8DOlP5AAP2lX
